name: prodsegmenter
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  # Python and core
  - python=3.10
  - pip
  
  # Jupyter and development
  - jupyterlab
  - jupyter
  - ipykernel
  
  # Core ML and scientific computing
  - numpy>=1.21.0
  - scipy
  - scikit-learn
  - pandas
  
  # Computer vision and image processing
  - opencv
  - pillow
  - matplotlib
  - seaborn
  
  # Deep learning - PyTorch with CUDA 12.1 (RTX 3060 compatible)
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - cudatoolkit
  
  # Additional ML libraries
  - scikit-image
  
  # Development and testing
  - pytest
  - pytest-cov
  - black
  - flake8
  - pre-commit
  
  # Utilities
  - tqdm
  - click
  - pyyaml
  - requests
  
  # Pip dependencies
  - pip:
    # Segment Anything Model (GPU accelerated)
    - segment-anything
    
    # Azure dependencies
    - azureml-sdk[notebooks,automl]
    - azureml-mlflow
    - azure-storage-blob
    - azure-identity
    - azure-keyvault-secrets
    
    # MLOps and experiment tracking
    - mlflow>=2.0.0
    - wandb
    
    # Web framework
    - streamlit>=1.25.0
    - fastapi
    - uvicorn
    
    # Image augmentation (GPU accelerated)
    - albumentations>=1.3.0
    
    # Video processing
    - ffmpeg-python
    - imageio[ffmpeg]
    - moviepy
    
    # Additional ML utilities
    - timm
    - transformers
    - accelerate
    
    # Monitoring and logging
    - tensorboard
    - rich
    
    # Performance
    - numba
    
    # Configuration management
    - hydra-core
    - omegaconf
    
    # GPU-accelerated image processing
    - cupy-cuda12x 