name: prodsegmenter
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  # Python and core
  - python=3.10
  - pip
  
  # Jupyter and development
  - jupyterlab
  - jupyter
  - ipykernel
  
  # Core ML and scientific computing
  - numpy>=1.21.0
  - scipy
  - scikit-learn
  - pandas
  
  # Computer vision and image processing
  - opencv
  - pillow
  - matplotlib
  - seaborn
  
  # Deep learning - PyTorch ecosystem (CPU version for compatibility)
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - cpuonly
  
  # Additional ML libraries
  - scipy
  - scikit-image
  
  # Development and testing
  - pytest
  - pytest-cov
  - black
  - flake8
  - pre-commit
  
  # Utilities
  - tqdm
  - click
  - pyyaml
  - requests
  
  # Pip dependencies
  - pip:
    # Segment Anything Model
    - segment-anything
    
    # Azure dependencies
    - azureml-sdk[notebooks,automl]
    - azureml-mlflow
    - azure-storage-blob
    - azure-identity
    - azure-keyvault-secrets
    
    # MLOps and experiment tracking
    - mlflow>=2.0.0
    - wandb
    
    # Web framework
    - streamlit>=1.25.0
    - fastapi
    - uvicorn
    
    # Image augmentation
    - albumentations>=1.3.0
    
    # Video processing
    - ffmpeg-python
    - imageio[ffmpeg]
    - moviepy
    
    # Additional ML utilities
    - timm
    - transformers
    - accelerate
    
    # Monitoring and logging
    - tensorboard
    - rich
    
    # Performance
    - numba
    
    # Configuration management
    - hydra-core
    - omegaconf 